# Generated by Django 6.0.7 on 2026-08-02 11:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SITE_NAME', models.CharField(default='MintBoard', max_length=20)),
                ('ACCENT_COLOR', models.CharField(default='#2ECC71', max_length=7, verbose_name='Accent color (HEX)')),
                ('BACKGROUND_COLOR', models.CharField(default='#ffffff', max_length=7, verbose_name='Background color (HEX)')),
                ('LOGO', models.FileField(blank=True, null=True, upload_to='site/logo/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['svg'])], verbose_name='Logo (SVG)')),
                ('favicon', models.FileField(blank=True, null=True, upload_to='site/favicon/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['svg'])], verbose_name='Favicon (SVG)')),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
    ]
